# Global 全局配置
site_analytics: 
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: /images/favicon.ico
snow: true
click_animate_js: false
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
cdn: false # 请注意这里是静态资源的 CDN 来源，图片的 CDN 在下方 jsconfig.main.pic.CDN 段配置
check_update: false

# 自定义样式
customStyles:
  images: # 图片相关设置
    banner:  /images/banner.webp # 站点横幅(/images/banner.webp)
    background: /images/bg.webp # 站点背景

# Index 首页配置
index:
  post_type: true
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  archives: /archives/
  friends: /friends/
  sites:
    submenu: true
    author: https://drfengling.github.io/
    project: https://github.com/Drfengling/Drfengling.github.io
  playlist: 
    submenu: true
    toplist: /playlist/
label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-file"></i>档案馆
  friends: <i class="fa fa-paw"></i>好伙伴
  sites:
    submenu: <i class="fa fa-link"></i>链接
    author: 浅梦博客
    project: 项目链接
  playlist: 
    submenu: <i class="fa fa-music" aria-hidden="true"></i>歌单
    toplist: 飙升榜

# Footer 页脚配置
group_link: 
contact:
  weibo: 
  mail: Drfengling@163.com
  telegram: CandyUnion
  twitter: 
  facebook: 
  linkedin: 
  fediverse:
    instance: nya.one
    username: Drfengling
  github: Drfengling
  rss:
timenotice: 本站已运行
icp: 豫ICP备2022011311号
psr:
  
# Post Page 文章页配置
posts:
  show_cc: true
  donate: false
  share: true
  comments: 
    provider: gitalk
    enableBGImage: false

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: https://disqus.skk.moe/disqus/
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  appId: XYhdixCFbfmqQJcY5athgHfc-MdYXbMMI
  appKey: qAUzszcIsA6WsvRkeR2azXFs
  visitor: true
  enableQQ: true
# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/reference/client.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: https://shtxy-3gjbjsx5d5549b0b-1309576270.ap-shanghai.app.tcloudbase.com/waline
  visitor: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitalk 文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitalk:
  clientID: '67075d9ed7922a3c9791'
  clientSecret: '50ce067bd2bb3d9e9e48d56804da1a6d25e7bf16'
  repo: 'dryunment'
  owner: 'Drfengling'
  admin: 
    - 'Drfengling'
  distractionFreeMode: false

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitment 文档](https://github.com/imsun/gitment#methods) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitment:
  owner: 'Drfengling'
  repo: 'dryunment'
  oauth:
    client_id: '67075d9ed7922a3c9791'
    client_secret: '50ce067bd2bb3d9e9e48d56804da1a6d25e7bf16'

# LiveRe [LiveRe](https://livere.com/) 评论相关
livere:
  id: city
  uid: MTAyMC81NjE3OS8zMjY0Mg==

aplayer:
  enabled: true

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: /images/avatar.webp
mobile_toc: 
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    pic:
      CDN: true # 表示使用 CDN 加载图片
      random_amount: 20 # 表示从1~20
      filename: "images/thumb/thumb_{no}.webp" # 相对于主题根目录，表示文件名的格式, {no} 用以指代随机的编号。
                                              # 如果包含 // 表示使用指定域名的绝对路径（例如第三方图床服务等），那么会忽略 CDN 选项
    createTime: "2022/04/12 17:03:12"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: 
  baidu: 
  bing: 

# live2d
live2d:
  enable: true
  display:
     position: right
  mobile:
    show: true # 手机中是否展示


# Friends 友链相关内容
friends:
  href: "friends"
  page:
    title: "好伙伴们"
    comments: false
    description: "好伙伴们在哪里~"
    updated: "2021-01-18"
  list:
  - name: "猫猫①号"
    bio: "喵~"
    avatar: "../images/avatar.webp"
    link: "https://drfengling.csdn.net"
  verify: true # 验证每个友链的可访问性，炸了会有提示
